apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    k8s-app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      k8s-app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        k8s-app: {{ .Values.name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          {{- if .Values.port }}
          ports:
            - containerPort: {{ .Values.port }}
              name: http
              protocol: TCP
          {{- end }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $key, $val := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.secretName }}
                  key: {{ $val.key }}
            {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $hostPath, $mountPath := .Values.mount }}
            - name: {{ $mountPath | replace "/" "" | lower | trunc 63 | trimSuffix "-" }}
              mountPath: {{ $mountPath }}
            {{- end }}
      volumes:
        {{- range $hostPath, $mountPath := .Values.mount }}
        - name: {{ $mountPath | replace "/" "" | lower | trunc 63 | trimSuffix "-" }}
          hostPath:
            path: {{ $hostPath }}
        {{- end }}
