{{- if and .Values.image_updater .Values.image_updater.enabled -}}
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ .Release.Name }}-updater
spec:
  applicationRefs:
    - namePattern: {{ .Release.Name }}
      images:
      - alias: {{ .Release.Name }}
        imageName: {{ .Values.image | quote }}
        commonUpdateSettings:
          updateStrategy: {{ .Values.image_updater.strategy | default "semver" }}
          allowTags: {{ .Values.image_updater.allow_tags | default "v*" | quote }}
        manifestTargets:
          - helm:
              name: image
              tag: tag
  writeBackConfig:
    method: git
    gitConfig:
      repository: ssh://git@git-ssh.aleix.cloud:2222/alemuro/argocd-homelab.git
      branch: main
{{- end }}
