{{- if and .Values.port (or .Values.domains .Values.cloudflare_domains) (not .Values.disableHttpRedirect) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.name }}-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
