{{- if or .Values.allow_from .Values.allow_from_cidrs .Values.allow_from_namespaces }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      {{- range .Values.allow_from }}
      - podSelector:
          matchLabels:
            k8s-app: {{ . }}
      {{- end }}
      {{- range .Values.allow_from_cidrs }}
      - ipBlock:
          cidr: {{ . }}
      {{- end }}
      {{- range .Values.allow_from_namespaces }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ . }}
      {{- end }}
{{- end }}
