{{- if or .Values.port .Values.pod_additional_ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  {{- if .Values.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  ports:
  {{- if .Values.port }}
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  {{- end }}
  {{- range .Values.pod_additional_ports }}
    - name: {{ .name }}
      port: {{ .container_port }}
      targetPort: {{ .container_port }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    app: {{ .Values.name }}
{{- end }}
