---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: default
spec:
  encryptedData:
    api-token: AgAK4lU1O7biQTXC11id0Y1G4RDc/wc3vcHudxesMZKoJxEWjeDNMVBWr8QKVymnXRCsE+H3omfW/ca1KmMY1x4VNkc3yduB8L3HBpJQTuQZBDflysRNqncNbZZeOkT3WX+p6bqqNEGRSdjz66WHFb/4vmoxaRZxhynuw18W4r4+lIXsbUOOGIKywOGF+loSHcGfiVLWUBY20GyIrCZbOFq+gHt3XQtt1VBffM9aVxVn7Zr2oDSJ7Ypo6jncCRXvTHfStbERvJRC2pmSYFyOZ81qGDpriVqz2MUPYlu7lqr5XpZvxvDypw92cCnZETQu0QqdVUyCrweQgeVCpG+X90Dl7WRYN48SP88zMgFjuGExVVK6xd9trp0hCIbOsrQEoIykZfS45NAI5APbvRi+wqIaTuB7C4cRduFEO7Kt0xhURlNKOohdztifXyzWk3wrCAgHGTeGae8YYb4SMZTqN1kHWOE2UjLzowezDk+WHgK2gZLTV1eGWm2gLZC9M55X0goNtWeS7G8yjgPJhKTwJob2uuT94ab61eIuCrQl41gL7+hvbob4cxAyZmZyP2WnsysV3EIOgBejq83jK1DCnhRbVhp+Lx+XxKCc2NPjY8o3O+2eZM1az9IWlkmVX3X1NNAvnDP6NC5I3YWcQtIRDSlEh1vgUBQCN8TGhPWHNZUsL71aFkhjvWXQp1mt2PTI9gc7qsoBhLx8mvR4RvFwSdWTOEpngKU4Z2qL0wWGZpRi+uw2uIoaVN1D
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: default
