---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-cloudflare
  namespace: default
spec:
  encryptedData:
    CF_API_EMAIL: AgBVMXgvSNVCFdlNe5OgWHRLvkjkkv7NGR55LWJTu/6lLA7vjHi3gCW3AuFfwHmzpi7yR/77A8ZkoTeAJ3ylkBoJOsDog/uayj7DptbNWcZtA0h/3ffxUEteHajXbI6zeLq6rWKmowQiJkwLZHlo3ZVvYaS1FJKjQoPuUxQqMW7CQSTDcOfjAUhoDSzT9ro1Ml9vhSOdJQ6ehBzM1hfX6b6f2aczB59XzZwvfEEmbYULM2PHBMaCg5pdrjeOMxYakgv8DvKK3KT+cE6vJMKVWkPTBLjfuvbHQz51HLHJA6sWfAAHrHrbQ67g+xQ2HKEqpTXqivGUiEL8RT7BGaTidgnpSS3tHT8+4DjkxaL/xkGBJJZMNKQgPE9aj+im/i7BHvIdT8obVLzQHBAvuUHCFNHoX6lcco4FwcSEtE7Temn3ryRtMrj8Vk8PZMOWdi4zeUcZ1mrjTMcAFNBfiB1edSma9Qtv3T0ZWsKBUvnnAOWVooT8NmjaPDI0AKy1a3iwgoob1kyfnH+nX7wkSbGnSwf5MJpZ1fygvth7tRRUt2irQwDQCcVLesIplGXrWac2iP6vSVg307r41tUFxPVbpf8pFJoX85494G/y+OXQPjRzwNJ+zu5w7+2qoRpECOBtVJzv2QCry/P4ql6ujhk6lGRIyR0omfoWxpXhpXkgoJdeVi8uPF2Wl3wt2i3TlPeFpTrVtarPmOJxKz67TasbYJIWlGnp
    CF_API_TOKEN: AgAfwZVw7N7vs7bzp9V0U1opq5pzb6sbAdZ7gSle3Izaj+2taTir+ZoZ4mW9vMpb1JBAJHIjiX60iZX2ijKvD+1dZSMWBSIrSDTb0Dne3WLLfsCLqx+BWnTvnWs2JolSY5izpUIuldk5W2LcxuzwAcxV4Q5Zej/AexjI0Z1RmFV1KoF1eTu94ltMREH0aqO1wF8NjmSEfKJsHW6keUcM4Zh5gVnX6JwX4kI30MzimAuwAZjxN5wtXzWvQ1tM6P6cB8DznHd1mKlMUd0xfpVa/XKDNxqpXJkD9qDCvK90gbbLdCYwydM87WZVrVhtWfKTILEjKbya4rde0zu6VSdfmy5kDamrldL7SnR8sW35PXVj+UlEUotAw536dFZGMklQUzpZ2IxJb0PjsYov8b9DS8fKJ29nR24ldzrbxiuRFT848JBvmifUGYej/EHwa3a3rl7vkO/afIsB2aJSrCB4T9EIAfya+QYeqVby72PYSoBoFuIqDalqK2W74ssdnXJ1rJdorz040K4Dz6AdWYKY4u/llggXb4vTI8bw6JanHzUzJU7vTrjYC4SGEsq57MeB3tGv0qtADelS8gAglm6AUDIA1XU2m1F+cJFIgbatAusNTMQYMwUKBQ1dBXY3S5I6Q6XI7/UkBA9aresWiUsUQf1j8+l5a865QRjnqtBLUWJ/5U+XHeZ0Ktt1aiUwAXQIKbCHIxZPLJDd9/MF64YYHhZtfGhFeV+7kUBNgjoQwYkvCcze4mBhh0AG
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-cloudflare
      namespace: default
