---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-creds
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    auth: AgAzj/xTPWdlQCduswJkY8pcTZoc1df6pEnMqw9Il2Xoc/Adqu6ckDArkAmPAzyTgiOvcX7BnpV4No/yb3Hpbi8HHpUNhQkjh1zp0nJVAdvp/Yq718Ce8Pw36CmO/59Ht3EBu9V7x1Pnk9JEW5XGhnmOLbBq/XO+RH5tjqNL88wGaQKFJ43x6BE2S1DWefYxp4kBVGv/MI7kEOjx11cyCBsAIzUj3PiUbxA78BZ9GTkFocuZPHBwmOlKZsiCBSDWtoUjIgDsRddIEzRj2ZxQhu3yH7m1WmH5AtUI9sxKz5sIYDq4cM/mbPuUCqmVQDyHR4hsOlEk4BL2ABE0vHfbjWedLVUTh1B7ytPRqd0KT7pBoSqiHouV+BWr8GY+KTU+jED6VxVLTow7zFEElrZ1a98bamai5eozN9OVvYK5kLtbV2dfq0GBLFJGkNr9SQdz38g+miE3nLsHXzDF9xZvN7xws2NVFVb7YoMCIr0hfMFl7K/M0b46EiUebvk13scom0FupdyD/UK38NNhGtHcUbeP3/sjlzzowmQM/0oCfGsdgcaIaUxCd2mEfHPw0g7O5D/D43sZB8ijuCsLcj599mw5Qqv5WeZVcQRUUED2kCe+1c56Rb5s02pCQNoq6SHmcMmh1dZ52DD44ZBx0XHnLv5YAR46Ybsyb2wr7ZryvlI4dWsw7gFFVamll3jufFFygi2nq3B9HT16NuE0O0fS2sLfvEed85mYiIuzawRj8MydibBp+HsS0PL6+QKujBZ+
  template:
    metadata:
      creationTimestamp: null
      name: grafana-creds
      namespace: crossplane-system
