---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCKxv613R16LwIC4KWRpYtATY46On1GreQABp5sgunQTAk13S2HVLrpFPzDV2wbqvXzI2dFa1TESuokTL1w+OCiPuCRLXqOXqcWF8qaSXsN6hC5ymYbGRKLJBJ6J3x2qpbvbjmlQ+INQgfRgEHZiecPpMEQqnEEnWW9xNN8IOVdVijcVYWalmtHHM6iQ9zPjO46mKmucYKB8pi3fC9Ff5lobTCaEkYqwTDndgf0+3e9K3N0UtwHkT0eDv2jmAy44a03FmVgUSNVsp3xlxBfz2nlz3ZqjJNYk4FBw+SO0Qp2DKp5bKz3kjeouFv+m7ByOvFs/JwH1vsskkdgGIijXpYFNxfPLjZQj+aVo2kZpI61RaliasSHz3lZDRRG+UNRinVfp+wfHXDGgiM1kZwU/T+ygKt2oWVO6A6to+x8TkJGzPW9EMYFNywbfB3wQBm9XJQP6yJGo5cOhNvf/OncSBLz44cxnCsdQNGtzx1dzFd7hyjl/bY+/iwmDi9VIQQN1Bdjb30H6sBKDO8ffXrAQez1au44FbL4q7AAw9ZoasBLreX7W5jsdBHOD7Uc+nUR+JNqy6xivdG2DLs4cT006wyIBcP16CBvxz2Gzi2H59wwN2/MjK2A6zfGQjKtpkKKQbuewNMASEdS+29pGurEsu9aGaDY+MnyJeua/IbCSOu/Q2Dfu6FcORyLhXec0UVQt7fYfKuLzx76edU6e1ElE3ZhFYrn4WhC/bMg7G4Le588kTrGrwSSWWuyeksGfhf4yB31th3/oL0ptzwrRsWsX9EW6/IP1jSmDic3hFofMRveDehds+h2JTZlDwEy0A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-creds
      namespace: crossplane-system
