name: ""
image: ""
tag: "latest"
port: null
domains: []
# Mounts in format: hostPath: mountPath
mount: {}
resources: {}
allow_from: []
env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Madrid"
# secretEnv in format: ENV_NAME: { secretName: "...", key: "..." }
secretEnv: {}
args: []
serviceAnnotations: {}
nodeSelector:
  kubernetes.io/hostname: worker-0
node_selector: {}
