apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: argocd
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '*'
    helm:
      releaseName: argocd-image-updater
      values: |
        config:
          registries: []
  destination:
    name: homelab
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
