apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: argocd
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '*'
    helm:
      releaseName: argocd-image-updater
      values: |
        config:
          registries:
            - name: Docker Hub
              api_url: https://registry-1.docker.io
            - name: GitHub Container Registry
              prefix: ghcr.io
              api_url: https://gcr.io
          # Activem el log per veure què passa si falla el write-back
          argocd:
            serverAddr: argocd-server.argocd.svc.cluster.local
        auth:
          # Això és important: permet que l'Image Updater llegeixi els secrets de l'Argo CD
          git:
            enabled: true
        serviceAccount:
          create: true
          name: argocd-image-updater
  destination:
    name: homelab
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
