apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - chart: cloudflare-tunnel-ingress-controller
      repoURL: https://helm.strrl.dev
      targetRevision: 0.1.0
      helm:
        releaseName: cloudflare-tunnel
        values: |
          cloudflare:
            secretRef:
              name: cloudflare-api
              accountIDKey: cloudflare-account-id
              tunnelNameKey: cloudflare-tunnel-name
              apiTokenKey: api-token
          replicaCount: 2
  destination:
    name: homelab
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
