apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - chart: crossplane
      repoURL: https://charts.crossplane.io/stable
      targetRevision: 2.4.0
      helm:
        releaseName: crossplane
        values: |
          nodeSelector:
            kubernetes.io/hostname: summer

  destination:
    name: homelab
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
