---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudweatherproxy
  namespace: homelab
spec:
  encryptedData:
    HA_ACCESS_TOKEN: AgCkGwrsv6Y6M2+xpzluRpv/u0XmrcoUvlruyKKJgpGS3zN9iSnNwa8YtBqaDn2dbsJ3sPWKOFgq8Vyo2PhlUFZ0yencj7UcHkIM2mhtmo7VWezv8Gc/D+I3edRH+wxDnq7dVU0FkeYCNgLylDHTzIUvXcx5JhFyAk9Sg/QjJ+Qz6bCYs0EovBwq7x5touo3XqvCHtbb7EAgWXnu4ojiEgh5AxGC3Yhfsuqt0zaiCmOvGuQYgEBMfo2FtM3JsWVKZGdTKNV/ieTpW4MU85F3UcgXYxuzK329oz5WLjFwfWpe+3xvDlq+yMekiF0X6YmTpz93l2sa5vkSW9mE8EbyvNrNVMN6lV6nsqUSLGGICOHbDmIpXgMLsfLIGu4UeF2rPreke8Vpf0fHxMwdoH2f6x8twrINYoC2T4nhVZUYvOj+u7N3x1zyreVbdmzhAt3hFiKMsrrY9BD71g1Ikay07Ikq5HHgNyoawq7qMUiAbd74xWIzOrWhFru25ymAsdN77sMRupSZY32KFUwocszqtIoFNljgSfQ/UyNuJqIg9tac3IIJHBk0mpFsLSMH2Bw4Hp7RJsETUkBaK8WKn0cp6l8OQFGdTMMuPAAzbmHhFgR1CAynKT4BPhofZJQ5ykYVjmUIL/m97zAVsyzmCdiEFQx3nnxl+4CYHLg6x6/C2uYWkGulB394DK2IkAfCMurdlN6YFAOs5HieXX8wVQ4HBUPQ0o5k/xga24b/gs/IgkjsXTZjoz7XyEc8VROsVxrmDLBIO6eqOnoDv5k3GZv+3MiTB9wmMTNOJKjrIxP03DjQdOoZIoZnI2nN2WFRnLToavTQqnyha6rZMpHiEFAgIHToBneuYFV1oV7nOxA4yl0WVsS0kzDETJgezR5K45V0CmhvMJrnNo9pj86ohL8tBRjAdTjZjEi7453B6jv+VsPYfz+si6zbfH0=
  template:
    metadata:
      creationTimestamp: null
      name: cloudweatherproxy
      namespace: homelab