---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns1-creds
  namespace: homelab
spec:
  encryptedData:
    PASSWORD: AgDZVN54VES0KoJq3cIEX7LjJLYNgAcP94dYO2KbZxEbh/xmq6nwgO+XH9t1BkHzBBP9js2CFP/FwRWqq3/RffKar+u5fCTl4ahHqkquXKGTynRS/j7PYl5eqoYkeDdXZTS3etlnWX53MRShRmD+dQVtmgu059rG+PdX2IchQBtv6cIeci1s9n+ORSugvREB3afvEVk75MJCyfWxnKdFBA9a81ofv72kKo2bRQcxHzKdv9sa0W/5JBgFyfFem7q0W8i3almt7CsAs3JS9SjY+k6gsfFyUl1ZYkgWjzLq2QMn57huOqzcxZo23XTBrg6yYIJhRssZxY+KPoVOt1G95Y56eP02egk5EJsBDRbuKeCyTUE4iqrf4lh8wDDcwLsk2ACA6gnRePXvGQ8AuJxdBNvVGVFn+ubJiqQFrIBXAj1g8kdT8M9QNJ77rkHOqwfkNCIi65dwBcn9Y/Oegid1dug3qHQJfzn1xid3f5Ropf2H3JHjwbq+Lg1Ds1fj0lWiL4mRqh8Mv1v1WD8DPs6WFtpoPwHE8y7eWXb25s0WdC6bLr5UQ4qTSmxSK1aZH3g3FM3V5sva+BhWJZhP9W2gtj3aDE2cQtchALU4Gj62D+pSgHZcuDtJuXVW91eE/6p1TAhjICHSvJoTEr72ql3cvCaDU6N38lTeDZfg0ZDaZEbWT2tePyS/oPiwogZ9pIS5oieEu++cqX8hxHqHTGjo/KSm
    USERNAME: AgB6VRefqei0LfBkaRyTtp3YTtEk7XJybmgbBSa4mlEYtQSJ2VulrXvR8VUVIGA9V5TK9uy2mxK4GWXEUOfIkPnWoqlM5cnbA6TQVsXCxGDn/faqj4CkhUz48wWxb9z75+dHLlv9FNdSlAgfw7JAaFzY7DzmtOqTAb+VfXKp0N+ANsf6P4uQnFKLfKt0GJgYBptsCgc5d2eeWxS2reXSprAwVMq2gPBdlLCrw2ocmdmE5wS9CDl6abs3ckU57+Or74cdfMIpA/Riyh5jW/Ar4T8dL1EdV89TelSLQsHnyC5meK1u8JYvl0mw4b5vHPqM6Ya+NlT7u0a5fG4JprBfwiRicDUdhnJe3veb17Umrx+ouwQv0ZBXDfIHv3T4qTTX3BBvHufa1/oznIJnm3uBVk7dRYzlFtX9gTgcX3G9d0BcYUHCpAZKmJnwjHgtAXCiBvxjrGzr4mQ+u8MGflvgw6ehA6JEgjRfRHkuVJlH+JBveeYEZEHPQJafZvJERp03940NZzQ89AEbTQsV5ez39phUfDCRdFZ+/qtn+Xor1pighTY9PeW5gUEYsQHpFC/DSo5AdWimPhwf1rlBtTAMhkFM1qICSe3VJHKqL8PaIHfc43I3kMyFsaUguFAOS7Vf74lwgYDKy/QdQu+btZor5+sOiyip64SoI7+lgQLsoG3sLxqhFCmupZrgZWxBp9ravWI1jelCVkL7
  template:
    metadata:
      creationTimestamp: null
      name: dns1-creds
      namespace: homelab
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns2-creds
  namespace: homelab
spec:
  encryptedData:
    PASSWORD: AgBamxUPcFOLBjxY1X40hxAoaf0NBnUoFvgvyRvT6Gu4B0EGtMq48dZjzKZJCgJPed+nLlrVKwlZygDpTQXYjYoFN4zlmSR4wuCTf7L8tE3UpZXHigO4FwJZc1LJPFBp/wc+Xh1qtHJb5M+BRih2nwgZr66QkamqYH0KoBJxQs4qihz5Otlo9Ire2w6Ki4pE6xiShE07aOL5IZmWG7g+JaC04XJCPs8aXjWe6MD+sxYoGm/NkRuRKO/HBACNEpRwcWsi8oWYkRiSnxU5u5z3vBI4i3YKAKNi3iGphtZi21bOuEcFJuAzER4uib3w5Z7xD4+0dl/lpWQ5Ep3flzbzkErfXh05M79HrH2ATLQtj1sXb9clnZC8dIA1y/+WXvgdOSWl7Ne7XBRq13vXqyiFblWug4bRJEIP0ukN1YWR8rDE27J6Na7Tthh6kHdmaROAIFjo+YD8LH3wKtDuUIJmYa4XglP73UGQA7yQRBcf5oBA7Bp5HgloMergYUfMi2BIR9r26C1vBQ8xY+OwfPpzdKDRedeCJOsGXEXY50IWxCVVEHAAI0R/L5emkMFjaOuD3npHnWykNYb7ckkJkss3HD2zJ/JKvY6QLxPJsSMH55Tl9Vtsf0xY9HIitqILvTxdTeMlCS70UqaB7bAitWnxp1dlMhM7/GGDPh089wO7g73esBhkHXAHmoFu4Xx1gU3F7LYsLFDj6qbmIo5ogqkGRyaf
    USERNAME: AgCO4Vb1GWhGMC36+oyStkk87hkiPUs6e6HKdvlVEYovzOthjzC0Mz8RlcscbiVbDyWBzHOIeJJBrXtPczrQFb6428JE5EHC2Ccty1DSZdd5jAv1r59A8Ekz8Y4jdO3bx4JdA/aL1UKEFiAAH0gKKBxSVgG3A5XlF3Omb9EuVPox/PIr7LFjrwRV5N0G6APTre8Max2Amsbq7tVcsYi8zEG2jMVsk8wbjR+dweBz31TljTpZxDxShH8EPIsMFQdQHf1iwP12/3KMVCEx3wZ5T8g4h7uPuBcFmEf77bFbv5mhIm8K60iovSA5BGP9+DqkrCO1/RIvMkhB8W0qC9oaM8cQt2tDn6hPdCX5Q4RQ3RJfWiH+aNzjKXRZf08Yw7fqCp4yCkN6alHzwPzumaMr5wpxjG9gfLs4GmdbCIkRy/SAcLTxlDgPgNz0NVxqFa4edWpfiDmLApYEqV4HP+jAxXTJUObYGh6rsZ63Z1w5rbbUBsTjLSOoJ7vuFByjr/lVyhlliecbtHzsQ+xfmTBR7o1i7c1UvL+fLy1pX08tXuw6jk92C55mlUtQHr8dSOMQb/Bvgy21/G1WbDIh+nZlZT5yi7m+NF60WrabK9w17Up4+nx/bH+UoxR7TFovL7kFmMRy3QV3pOJOGgso3WCUValFhD3WZwDycgM18asFnLFereDyueYeEEh00TMBef+9JTZZLXPHVVkg
  template:
    metadata:
      creationTimestamp: null
      name: dns2-creds
      namespace: homelab
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns-exporter-creds
  namespace: homelab
spec:
  encryptedData:
    PASSWORD: AgDYg7ZIaQBfY1mk23UGYZ9d5g2rU41EpVFOo4V0TJ55OSVjKY98PHwvRZQ/O4LMtCIWclsKBOsHgChG5yfRb8jiBKZ90k2CQTOh9BFraZBuT/+TJYsxncMjQSYmgUvyqHDgZO0Cvabi72if67Y5eJ1SiJ31zNBHfJm3s+EO4pUu3NGRzb7ZHSWYRAPu2VIR4v/u9G6GLgdx4X4+KA4SPeeH6mgovsWV5fUHJDULby5CnlyFStbTglHFmOhJ+PmphsGrdCInTI/ccC31RipniHxzaBJ4ZBCUEgQQO+RU6WzlUKQu8FXEZGtNxpP0svx3LETwVlJVBrqptA6Ry1D82pH5b7QkWmv3ukCljhEfRIuDgs8trpa1Hk/yf8f32OsyezmQWV831rJ9xTw+Qvqu1JyY10eDKkyvFrxXeUbx4Y7pVhCYsbu9rfbIOBB9nxGBjHWY9YN1a62Z30r6CxWdgiEY2H1UIO/SzOoQEfFdFCF+3ABFQqjx4u2whmHg2gEiUbpKnl3ou4pn7oWEf9bfBKj1u2noPFSBOLl2i6axBkgajouJuZaNgdRCvZBOxSljBdgGPQTMJKuUjJmNbSCXS0C0cfFgVlTaXyQKmQfBG+XazH5B7ZskqRi9NdQbRdfzhYrlRJV8TdBeHPhllsyaaN8gj4YPTyhO3lxqANFawg8UOll0RW/vSWlsVJhZI+s5FuMo6Q8Hpj8YEG0OPFyfs3hyLYDSKEHZF+xvEmjhfDjaKoI=
    USERNAME: AgA/MT3Jf7bMsfsHINuOeuqbFpvl3KncR2aZ1Dk2xgX3YtMMAIuMpcqZ2joieJgZ4AuE640twkh4PoSr25QGYpMUVOvHOaJqSGq22n7R5j4ybppW0Ua0ozvamoJef6Pj/RNoixeoTMSlYoFzpjE9+EH3xio7/3jQWEGbyBFCpQtR6Ela66ifpX0cICt81tZhxrK+86Cqw9ceF+xwU4dhWSwJHQflss/GKD+ksmfZ5Oj2x+At50VGKzbi856WXvWUbOgG7SBmJ1TGxy11pkdMumwwmM4fgRBviLZ+BXHG5mgk9yccqCUb/Z1A5feW/3J9w1ST7shvzHi8rbJYZSug7rzNBCSRJBEXRcIdUrlz3qK+Ef6dcAVFV5yqeN0jmznFhalaF/DdBVULMwjqSLfMqAOwP9NiM68kFiXmh1nsEgFCqB2JUIP/wI9usF3GK2olDdIZorGSx2lORbwDq8CPwNGV1bGY15xUWb7IGP/BFAvqPV6W8b5oqXgcH//WD2P6sXCK48H3VXVfCHE334QePyWpBYoGb9Mg6XIX4QngDMl9O/pzi89dAU394XPQfNWFVpNMbGOVw233jjeUN6CjkvpSXHa5cVMzgD/CGp5ehotBNn2hRiiZGT34KrcibsdEXGw20sya0Rgr/XMsNWggvtrY/ExR/u2hB80MwcPVN1IlD7dwBiQSdv9PANrPivLUhI1MaV2hbC2th3hXCQ54O10=
  template:
    metadata:
      creationTimestamp: null
      name: dns-exporter-creds
      namespace: homelab
