---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: emailengine-secrets
  namespace: homelab
spec:
  encryptedData:
    EENGINE_SECRET: AgA6Fi1KEieq5a04yJ8YEFYEsRs7Wox777sXQAsxObCYuYzUJlCGgVLDhdaU7iU8swm4Mwme3cDjNogaejdV/k/7BOv7OJkKvB8dUdYLJ0foeV5opBlJIudh6t3ipLTdPUy3S+sa/B0KR/K4IK3d1S4yegK5huc6c4hMllchmt1n1zulHTeiS7wT8GyOuxzFWxttmF4KmvqZrgPR3vkC/U/py7HSDdob3MdqpAJMrZxwEcCn01lT7uPHyfU3QRzQRL3MO7QEG4zygbqQIQTlVOeXRuUcEuVWqpPg22hQHJ32bSnJj4HGIX145jhalkj2zSjpVDICC8akZqrLCm3S/Kqb315yIVoW6Z3X00SUeB6NfSwT0A5pAeB7LJlmDhtoAQzxHEhpKZRHo5aXAcjkUFSBr53AMAriEhvaZ85QThuhU7G+fKrAsZ8riZw3jzWDc41bMUUyDPrY0wypq3Ep3i4VXMn4VuhD0IBc7/CyW54NdwPehsSdZ8EUxEEk1f18LW6k2hxdEtRzo4laT362XeXNNjShpVwuxplcvSO4bhTM6gHHyoWIhVqxGWjPUBtMPEVJqaFx3sF61VBL3Ten3HGGKJ7IvalKz1c50XESPtGEtAnLUsFuLuHNnK92qMY1ynClkvAWV016IWUdmBOaVikQQC7ShNDnE4O34hEPBOZISjH5r1muz9qC4FaKwgFU9E4FvBm2F3e1u2YtTrik+wowUwX/BG/DwqMO6pMZRsByyxUVj6OL2ubaVLRm03YNmsR3iC31jD+wLZbIheAOQecs
  template:
    metadata:
      creationTimestamp: null
      name: emailengine-secrets
      namespace: homelab
