---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: turntable-bridge-secrets
  namespace: homelab
spec:
  encryptedData:
    HASS_TOKEN: AgBc2xEP6HTza8BvbfWcxJFuC/+Me9Xd6Zy6w806NoA+GrUdW+dZ4H3VW6KXvlOihlSbEWueFsEH+E6I24SmCOwhLY/y65qK1rsl+xvRU/Tkb5M/dEt23g1ISmYl8NNWDG/Ch/MbqLqTzj59LJWQOFpXdsIeI4j1+KM7Hjh1DlNGGxvBALOk1tTOhjK13/03VPmuK0ibpvmt+9r4Ro354q6/ZXoGdMP390p7JnnXHHKSOfa9L/7RQjIeZ6nDMnsdN5HR6FUM6y3NyfqB03pwarNKlnmGqAOK4f4JvWlZNe5/vU+Pqjj5Qpnk4N6Vh+tp9Q+vD/WBoI6GyLqXmRVClZG3d9EemK3uU04zP4rR4oQNrmmS23zOfajOj6PkL86efK2r1nsBZ52+H8Q36FTc4pUoKqZRex+0tG3jEZnDvLAnyEuKyDT+uKEeEo9zm6yVpF8xOCbkLy+0s9FrAtYeEDxeAtXZZzbO9vqMvEr0cwGICUJoy35DH8LTYLZ21iCvFknToBvGf5XIEIUZ/mNtM31MllkcSsPy8/6RUlZF1hIJ7gBhs01IISp49zQtjPE6rnrS7Os0qFjoQ4o/aaKRw2TGXapv2d0kK1m8gO31KBTnxem6e0Y6dLAu3xj8DqmVGqFwUsvl4Wdm+AdL79twHRODQWW7vE4iosBXc5ddyZ13Qb2Rg+1oDHMJOqcNRQ4PwOSMWYnvEZ+GKY14c2C6Sfi4DGY7i+xm3xXMmA32tHmzS3XudUqjKTVWRO//o1OWONB11zNMbCPCDMvHkiPZiQLazjyby48DvRDh6HXCatZc2zdshCD5zcLua/uaeGeUwtDyhnLG+DeKniuF9sVN8NGvTU7EklE32Rq9opnRdCgGhfrNSU1M6/2ftqJ3yXmXIlg/F+0YUO0jeV289oPZsQvXNvsNx5ouEv0o5Dm2vx0/4YI6wDbx2X0=
  template:
    metadata:
      creationTimestamp: null
      name: turntable-bridge-secrets
      namespace: homelab
