apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for homelab applications
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: homelab
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for platform infrastructure and system-wide resources
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for ArgoCD configurations and management
  sourceRepos:
    - "*"
  sourceNamespaces:
    - argocd
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homeflix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for homeflix applications
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
  destinations:
    - namespace: "homeflix"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for homelab applications
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
  destinations:
    - namespace: "homelab"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for devops applications
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
  destinations:
    - namespace: "devops"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---

