---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: overseerr-mcp-secrets
  namespace: homeflix
spec:
  encryptedData:
    SEERR_API_KEY: AgB1s3SdJ96Gc5R4FEnOqrhDEloUvuXZ5pq9HOQKfIFgkN/eree6pjAOqk8oXWYGPT3JmzYyVwGeaUt37VtsSjhL02L1n8fizsNRjRsIMawxGoFH5qiqW6jwS2C1MKlO/9iTSjSDOLF+qKnAibKarWgRwXPzhGOAECh9izaBDSGOQmyHSXvZVcs53THFZifuVOqzesvzf6eY12/PxxVS+ABsb8A1Kk488BT1OewhcylJR57MTiegLUDZr8XycwKwP2+OVUWkhPkS57nbqQJY98j7XetvVShE6mgupSRudLrKo7wvGfRld5jKv7VNWJzdu6Zz65VtKg9LFeh3k+8F4qKJC4CHHxIXkJ1tsvwXUHrQ3uoMHgHHn5Ol8KvsADNfxEkaps8zT3pq6+5g5kGCDvpb1kAeh4kCjq/xU/hoamFQhkkd6a2N1RmCreIwQz2aDjmAo27ZQ9jypHVRQkpWbD+wPVY6yGbr9+QXuEkzaMSJbLwh4VM7r3WeOP8hnH7tyzCoHoOduEbfo7vsf9C+WtXP6jxSLUm8V1PoVZteubexAQn2j+m/hTKaHsahchkcX3s2n6qVnFN7JSyGz4IUe/LzpGLdwz0jwHtJYxyMYN7fbGBEL3E+tJ7tEA676Fq2IqMH1pPAVnP5fFDj+0N+qoSxRlMK/ii9ThqWNJG7e8A1nKUIVPqk/Vup7aHSnKZa22ZiGO7VyO26h9CeyMIwMtdhr+7wN41ykDDTw3dbNTL4z8/j7PjIWFBJClIkYQClFDv+fHZfGmDvFsDSFNBTgOuptNkNBQ==
  template:
    metadata:
      creationTimestamp: null
      name: overseerr-mcp-secrets
      namespace: homeflix
