---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: creds-github
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgBe0Uaon6ANQ6XjILo8pjrj4x+LxmmnrBuCvp2ldTWCn/sV+xmD+UBSthkYkfLhROFgFZ+SJQlpDogNvt93QLRpFLUE0RUSEYpHeEAWS3unQQTlS7aMAAYuUzVE2bFtvuIe0Wbi1lXZqWNdSLzv/zF9iTFE68lZZvmgNjJVJGEl2v7PexFeahN1sPy+OmZEDtdijAxc2GrEiYh9KIRMs++pqeM4etAx7Udmja+Sn+0gtL7hD3Z9PN2dPqpw5/fbFXCAovAwJqb1Sb2KM8kRvNZtfjJYjDIFRudi3TuCX5jANvu0VBBv2PeAnggQOxrx4Agxy4WbwfoeUYQl3rHEyYU/0uzo4d3ExCxitM0VjWNRd+0A9hPX3nBl/AoEmXHUgPFcbhnW8qcgEMKPNbCEtlNnccc1mJpB5d8iDfj++2cGnJKh7nqmQhoDMdWSff1bYHaZTx5NJr/xvAO2fPWO6gtM+N7Qapk4OVEMqPivMQEz9G1fLPrKof5SglcsOuwQtHA0W5+ekgouA8xnwnv/F49Z751HsUlDiYwlbcVkqHQXct8g1U3bt4gcHV4ST7UT9AOPAfrVRZCY80Y9mvWBRy+D5AyHvY1iy20v3IeZ8g+PolJoBAlheCgryrrK7DZuWToCZ+BW3750klz7xsSDqeN8/cwHCMLt/axu+UNsGnnbScUAo48MVnzyT9OieeNs7VY88oQjOp7E4PE8pYchTwSCQISOdDrmOU0kNxuQjucYSdwsUNF4oBdAFT58a56pd1dIoJKCP+Pxyy3Im7700OwqeL0ZYyizaVmeZbMgYrcZe9B2yXC0P0p12xlfkQ6wJu6hl9YWYb+SeslnNxhEqxR3ZuaD+EnMQlL//P5sQy5KpmMvKAJnCIfLqvJLOiYDL+3ThSjEPPGBtfiHMjc7+N/0B1ot+pWCN0q+jgnpNOzw1dVBVFL5oT9rVKPOeIKX+O5wQrHIhR1GpCKAIU+Y/V8kAw4EezWkSvhJTNgiuc/Vj9sLFwCGGnAVSinDpRz+f8yfDal+lJAUrJHVyOZDFwM0lNxjshJXuYyc84kEHtaVb7xTZJTyP72lVl9VSXLepyKnP9R0IhjBi4nxWsxWduo4+NRIE8ZKR5fGy0mMzqCfKcbW7nhqlBDJYmDCzDfCKsjgWgpN59Q6PThdlzdjMIRPbeLNOOuslWOCXzFzADjS5cyGkUQmV3iS+lH+lKoC6FJ9K+3IY9YSddb1s8ubVkC/6cNM/F1UkoBQrN5pm+JS578/aA==
    url: AgAkgW/BCXmAPTzna9ffhs4K50PO2ovn0V5Mg4qL4ma0e3nbRRVDYiUL/i4hY5suYSTsUXw9P5AE3Pta335hxGxD7MapQPuTxB7O1pH0/kkpbrp5HMaoBqQo41cm6aIeboOqYUFqd/WBruPBEpE1WTBHpDK0qH6TQepKWP2zmho1qZoKxx8Fyhv+JO/Wo7fKbwOLbpTOe3N2UyzjaHb9RieNLr+X7KJzQ40n0JGCjGNh5+gfLE/I7czlQnQ0R1qBsGYnxeJMWbntLr2k/5QvHKz4BvgXMrJGobfpx0YztsxcYAFtGWxHwpuqAcnFVyYaJNnDf8FcI12kf4VgIy48GAlzYiGNPFOzKZ5poq2+ECbmFeM3H7XVdkjnI6TlXaFgZ8O/Q3gDibAHYSQFNah+zTwrsFRhAmTFN6qIupBfaY3ztnk7X+2qkYZiLWuqiJX93WTlR9E3nB0yat6jx3rWBwKll88UyCRsknXzXhJ21J0EGTTu1xnqpNsQj8QCtDL1tnq82K3zY16ZsmbOHDeh0tl/bgqwAHgo4XvxQVVIjhR+JWfy2hRJbT0PgBL899tLP0SeVYWXQF76iWzHvZLYSTCUkc4Urck7dMhQ95zvAolHc1oRdhUK41RJHC/GKv4et68sRk2wKu2Z8uhFYr2dwLsXm8Mw14haqpGXSi+y6RLERMxDcRI2I9phoaVJGYTwWPGLdYSRa0DRdkPozunhw/+/bQfuus0f
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: creds-github
      namespace: argocd
    type: Opaque