---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: creds-github-kenga11
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgAnaJPZBdfY0HgT2gdu8cWgntvF5P2HeW7za/roQbPSHl6O+8kEezKzzKoo1on0AmPndCbEbBnlp6af+co0r99OWx2AS1GfYRjZjcJ10toVXNTdYMUZE7wrUvbjAe1TTu9H2L7nth7xA2xJi/ELkNWii467OstxU38/wx0HS54zLA9rR8Zlkjf1VSUoO7M29cpGhG3lVOkkMIgJsCvxIh0Ihgu0yw+6ZUy5GkDGYgHnYA+awuzNoZSFW6YA4+5wz5ZBz8whs62gYKxUgl74vWgUG964J+m6XMhsj445C4cWEMrJPsR6lgiw7ifwj1Xo3cYrvgecXAeYg+qBEjp9jSX84dk1MA02CwH5ySKgJW97MvgwwP5Xyq8dsam8sqSjjIO8MK89yBFMw7I6mZd8lwF21/uZBxHQV5TyH1mT2B32oJ/kq3rxEeljPBA/GVuljPI3O+KBEiRXt2k+JZ07cOD6L3J2Y4YNs9kybMpXsi7rETPYwyKtGhHvOiKHFF6ygZyFJaOxrz2/04FttmjoKpZ3RaYTAVeJydw0ppHdjMZbhaLvtsuEm9n1/S7utKfp7B/fWrGpgi39iYlx3sUe9XGKZ4A+Ps2A3wTi650MaKamsn76L3o2g7dKczpDf41TLxIkMUOS1dPpk2LsjlXt6hPrTRKCtHUWA4RXfnOnN7ty20aZgXGPjdz/NpbPhtk8O3ba/wxYTlgj35aD9e0zeW9zFhN2OjFsbpN6ZwhIuP7oSITe0/tnDhmnTk9i+TKWlIT4VShRxmahoOBg8T5dJUurRNRTU82j7ocOn4n2g95wl92JZoh4gzNrShGo4TZemrrehbMdjBTbPg9kGfFzSTmZusi57q/CRQpz6PONjaQmkPsa7sgSaJNwFQ6EvIM01kTey+i1uGsTudyxWiZVYFeDmpKe+4pmkVFcToiqefcrNu1/sGqnWo58yrOGfgPkZG4mMH7VEWx4wgTDVvxAdAJzp/Fksw0mcWmgjnw/b9rN1DJn/ycj9tMX/7kRnnnGjY7rpaEuElfrY9ZAWC3VITh2i1ts9KS+eW537jwO/zJgL62KpfCI0dHVjMjDxXU9Cqm14hDC1WjQpCWKdnH3ZFWxSyj2iAFVHlXsYJwB969E1V4bmg/XM2dwRBvN31bEIVEzg/kppAtfgjcwnfY30eTF/h15Qq+GTe727b/V2QtUlTSykZFhxgVhI2NWijuZsu22Ht8nRscUPt++2nF8QhHWflmUUa/mibp3PaZ5tTAi9pva
    url: AgAKyB5svjXHfuJqqznoSOEg3IcSLOuG8LHM2+m3RN8+/736mCEDHBNy3PQ1WgJtQ8c5W482o23oxdHyghznKzyISgwtPsYHnhF1U1/bPEIx8mZv8pCzhq4L/CdmG5E+tPixRf7/4mHbBY7tVioamTxQoRpuQc1pVm39/FiFN+jl1SphrrBVVQYkp0EoFQx+y8wlV48Q2HPRBhPHG8B3A9GibQMgTgdNkUwuGai3kgGnIbsylbX5KKWI61XxUuwUpH57sC2f+psWg27HOLm3pFgx8XJHnrTKNTVKeGta04DyfzrXaQ1E8l+sK/RNH5H/u2IRsXRkaZGnWyGwDetXvlNGhf9/MT4MdRs2xO+aUBBnOL2l/vPEFdfUJ6RiOZErGy9Af9rS7dJx/DFGDKFrszsMpSmMxQlDrZhjFShTU8K7NZPo5aDe4UCgna1svlngBW6PD6/rm+0XJlu+7yH4QwQTUpWIx8+4CWtsnh0711GBJkrlSQQMbrhhrtAGn7KCHtT9NF2HPDzAwIQtaG5q+53mAJQ5ctbyNLcyT77xw6uYNPPDA3RJQ+pn4K9SWLMTDoeOcce0rA93XUXTovz5othJoG98aKEqXQz83N4UWYb+8YW8/goLO0tiv3Kdrvpmljtg9fHSttQbIcEvo5YrLVPJJKDEi3/TG/jZmhiGBaYaezr6Nx+FR0VbRFhxfnAGA+53BIgDT+uuFAFy48nE9YMRV1i41zIN
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: creds-github-kenga11
      namespace: argocd
    type: Opaque
