---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: creds-github
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgB6mmcHcZq0LVvIafo6JzkH950Jk5QddoZsFhCgVV3Mxb8UyYXLoGIvFTBKje+abY3Nwj5A+4w9doilE+6CpGTCkKQUc7KxNoDwt9mbXPdMd1EBr4RALRHECy7UOtB9zdw6dUSWKiiVsQm0a4EfLdqpkKp+wfKSOnzXebDgK9VDy6zbfWbZyxBzYu+kUx7ivs/i4K/vx9PcPL4na7J8cWFW6jEJV3Lh8+cxWAlUbC3QZnq/YbuW5G1Bi3auVnFSrJmO3Mf9XX1Vzdpg87DnoPbWRMG5RAr08iOKByj6ZZrajw7Thmv34ZUpPY5OZik4AmIXy9s4ZvcbV9HHavw1CZ8FED1oNAqkyHpYTOWA0j8NoWfJy6/Kv7oF/V+51cBw1QtIVUMKafhlGIYffGltMbkhUV0/tIn9tISxBoAgXETmclh96rpklka5qmaHKJ+NW0d2+KSH60KBbkct5RxGD7wTM6UZRVp3nkopOxZT31/Y5SucCwq00r9U6Y5kWyWliK6bz9bik1yRMW8lQK+ZhyyQitGG5TCWUJ3UH/pogTn77j5zFUo0Sfxo80XOhnlHwEkBaSAJSJ3YUwh3VQlwmSFrOLmfQte9jDdlFcUfee/3mFYRoRNjBEDnAeuV8LzuWD9YnyEMAuv4dkcLNx4Z0yyQc0ngXvZrVZTOZPdfZX7T8F/0vyADkSCSYHGya6Xq0eWWeyvQJ/e9tn1+dzrRriwuuNu2/XMYCL3Hh7R1To+x07x1yhgR2Tqj3Mwy7KOPEvpbDqoXrRLczny3d997cl7NwyvpVeBpZq7h+ht3gjL2OmtYEjzkeKuiJCQJtWDXdwZvoouWfWK1aVOlD2fzGtc8oPIJWbWxMpBXqkgjax5DBr9qpw5na/D9c1iFe/HeBWt3plQo7pk1Vb4LFsNlLkhRA01pPSPKkfzAssfPJW95gm48awCv2l3Yp5ax1GnkeNIDGPnvrrlY9l+PiLIuMl+6eqL7svd+sYIJIpqvS+79fR6XobqjBF+N0yLd+nLTl6Dyh2uW9ynBEQXZtjUndiu8nfscGZQ1LtsetFDnZNAofDHQptlxStznnvgtHVXN6IWOu9q1TOW+PPcfz0dRLnfV5vOe7Sk0Njj2vbs0h9M6UmdkOLYa04ENRsVBZEwK3B6G651yRjwj624CvuW6QDkjDu1Rg5l2wwDbp+Xby5PRGLS1Ord9p/jmh2l9ffWZGg3FMzMcA2DIhaO99XgPGELlIPTwisUgO33evYQKG4ftgUrbcQ==
    url: AgCkcFUEpoBAfHP02KVbqgHvkZKN1AjyfzYON8Go105CxWrXa3KWwWjoef0rnRuxuFZsJGFVaNQBYnGMKVRoora0fGgr2zUQm8FOFaI8Cq327LFWNpdd6SANtL9zcwloST9n5Xyd3Fl7ke868y0TC0syA4+AD1fn7hPVj9/zjO/YgtpSz6YYTz7xb86omsvkRAaklplNI67ikl4mkydrRsAGo+9ozf0sXoWgNlAi5OIPwFvuAO5IUBydvLHG7ExJj1xd8kqGYIZgI1LwSmYo4iSOdij9EsToBArc+xwoN5dea50pV78a206krqM/XpLvLwtBUxYapkKUfWEDQZknBLXZL5wR7xtirQigSZoTWF9gSjjGbDG45wlz6kH2ZSEC7R3b5Liw3ekagOTLgK1IiZLizN1OmpSclaGuGQOFMY94gvsLAy9GEOSKnOlrkHledEdBD9qSvP+pmJGM3+SssMcpkwlESkZO5Hp8KitIxPu9FrrU6wAMaYv7UfWIwFlr658WpizReNlhQy7OQEat7YBnYrGKHOjNNPw9HMJcnbBPp6E2lI9avZa3RQ63VUOZ26e0BuT9bvMNfT9gPwAqAsvnw8tzsvJtr7QQBlx9sFQD4tPMI85qjF6RzLO+abyKHTyH6gJ+7RcOhiATFh8SFntEibFNgpQtTUuoczBuV/VK/Q+jKv6uadnkpSApB1oORhYt+V8ICALAV7BqZf5mDW9crUkhbWJZ
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: creds-github
      namespace: argocd
    type: Opaque