apiVersion: apps/v1
kind: Deployment
metadata:
  name: "homeflix-aleix-cloud"
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homeflix-aleix-cloud"
  template:
    metadata:
      labels:
        app: "homeflix-aleix-cloud"
    spec:
      nodeSelector:
        # kubernetes.io/hostname: worker-1
        kubernetes.io/arch: amd64
      containers:
        - name: tunnel
          image: code.as210469.net/nubulusnetworkopensource/tunnel:dev
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homeflix-aleix-cloud-tunnel
                  key: TUNNEL_TOKEN
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homeflix-aleix-cloud-tunnel
  namespace: ingress
spec:
  encryptedData:
    TUNNEL_TOKEN: AgClpuMF8nmkhtFy4iPkMnbAGnLnB3oVXtraj95xpwLhow5LziRvQlln49R1KLnZCnBsGeWMRuh10grvVoYUQQAj6xwbH/36kcJCLuDohueEswj8ho9Y8SR7ynRgcMEI2Sr1DXCF22gJQdsuv287gkpUTALWbmZib1vkzMbX7piPnYbG2GATsPHfyDMzpK8EjLSM3LNE/22/cz1RZ4AGiGag0kGbEOkrspIDJ3o0wwHvMHUhCDZpjwqjJvwKjRYBqbeKCNRMvsRECFCmyaljtDP9xAtZ76oubB/3iETPL5OrriEjPTIV4cVrGyl/wuYS4yj9082qtCALS+Tz4PvAZidw3m3IAZ5pg13jKGuVTln6WIdCncQbHqShK2SXx6UDYPNC9OkpgqapDJ6YIuJzKtlsqO3Mm8n0sJgEl0S+3dYN/29THvDZ6LxhYZqUoLjmGkCrZ36kDeMDHEJ15zpXSXUK0LSyYiNDF/jteUtt9f6GC/xMlGDY+4cLGm+7ToJ0lR3tYsskwK9emzWFHrDUDrWkrLRyr8S1l5R/lu0q2wQfL17OpDMUaqL+y7TsLFvfLjbJXz0vEbDNLhG4gauudD+npAf9oYeLv90c/lprK8BXhnYTwaMbNwdWmYGs6m/NNgWzPU/NfzPSbueNQwC4NrebrziDpY6jo/zmmIzsP4Cdu5tfSFhCdDDcMznd1uLSvjD23/OPBGwa1m5qMO1JkMzplf3by16i0NbB+NIFwlt9A2psOE6vfn80Ed0hlQrbSHQ=
  template:
    metadata:
      creationTimestamp: null
      name: homeflix-aleix-cloud-tunnel
      namespace: ingress
