apiVersion: apps/v1
kind: Deployment
metadata:
  name: "homeflix-aleix-cloud"
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homeflix-aleix-cloud"
  template:
    metadata:
      labels:
        app: "homeflix-aleix-cloud"
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: tunnel
          image: code.as210469.net/nubulusnetworkopensource/tunnel:v2.0.0
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homeflix-aleix-cloud-tunnel
                  key: TUNNEL_TOKEN
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homeflix-aleix-cloud-tunnel
  namespace: ingress
spec:
  encryptedData:
    TUNNEL_TOKEN: AgChNiYYNY+1AwLwkt/YhHmgo6IGl9xShwIVvD8y+WpkvCI7CQYicS7G1sDnpH3i4JTjvl5yZHoCbhjBFAkDZNLtNkbLnqe2YZNWcvsKNf78ih8SPxCj9/er+6e3pO388XTxbo26X71trOpLupx7rEP2rnxC+PtnSWXebKXk4KB7gTtsp6pNqZpXRnAteZV1Q62Lx7Az6RRQxFx9HoeRNvg64ElJ0if0pTQEHwGyXmVa//2rAAEQdtTz7wqZB7I4jWsy1ETANN02GvmR3zBgtmsh9EDF+qtDXGsCwKIT2RaGv/eY08hr4OpEcYihP4tPkJzi+0Oao9dDPoD2NNyobCT+fmF85TZONyLHNUeTybrF0fghR4yMAWc6Lk+lR3mPWlIUUC7/Ut26Ps+8MLNh9OUMQmHFM9hf0nWvXjxYfgjjnf5qR28QjBbO5T1eWktOltVS4EsVw/AdVZqK9kH6k1D+3aPN7A22//8G5UWCAjvfZS5PPJi4gcD41fjdDr3gbtI7wYDXHQ959ysSqq6kV5SDIzxh+ZuGP7+aNfiGw17BonRz4uDCKSvYrGZUP7TwRbaIfgi2TrgkDa6o9h2tWNVuMqeSgbmoz+l+TwKpnH/Ntj1W8GmS8hIvFUr0hFB52bLfSSFQlc7MUmPSCD4VvZnjmr8P6povyyBBEua6E/1P8F6nEcIew5SlclOR6E2N4wX1DxYgBYhyyUOPb+nQe2B0yXfuiS/dAQOEu+KaYKRXdEMfRdR8msj1bqq2nQBl8Rk=
  template:
    metadata:
      creationTimestamp: null
      name: homeflix-aleix-cloud-tunnel
      namespace: ingress
