---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: ingress
spec:
  encryptedData:
    .dockerconfigjson: AgBIjkjGRPsiM3fV4BdwH1vIPkA/xChRm+ytLUulc2LPssliO6D9juv6nHGQRwQllZSX2E8s+urKjYLaJflb7QxHE7kbvknENebWbg4X9up3lMmTt9egzltHgS8JIFe9XcTT4MItbSklBYlh5x9B9MQUwo+cIhBpa4xtkZ+8flkxyA9MbAPHvyCgZsIIq4IE6EaNdpn4TSBagOH0kJLjrfi7/H9EpF5cwpuV7lU3dFdj8g7P2RQVbPDtRdKjqlQMbfHqyb7txgjzMY3XvjaVdvX/r34a4SxUxv5UN21bm71s0ObU3a1lBCurSZ2Nsz8qylnrGkW+mUOmcKwBgh+Gi+6Q8HG4SsgS3JLDTmp9t9EQg5ZMsoxPSdpjYQ+Jvoj0lz+HlAi6g1BeMuwPiXRepc0cQF2xh+9udyU3oU2zJ90Wo8FN2W3u8xSZ0owfo5rGE789HHozYDFMU8GVA/JtMFqVIFn4q/HfHuBxzmUzvLFZyXHw3mfNvIwNNeuGdQuF1PeUfXl7ljCRLwd51ijLOlLedStrhQNhzWutowL0V3F9xaQdA7Cw4Et7Nq8dnBogJxAs+jfOX/EyPVGY4JuX5g71LPg3Ry9iOIdKm85kEpVyK+7NYNu+r87/kv+l4jx4VfQ+SKXEZOfBbg9Q1OlQHBYEddblDitO0Ez6nEpXnBn+vaQEyw3GHHMrCJjeDwGJRwkR+5NGwyerjwyziNLGo67ojnBxJ3Ss064o9CT6518zMXwiEgJyEQQOmT7syXHnd8hcpsxUk2YK8S+dWxsqFA5pPyIfIM8okDMl0663JHG39A+zT1BhVZi/kfGJODLc+bhzvxj3ghzcJ6qMIGBMZdXQtshUhpf5YQpfLAU5JSmldBftBSgb32ZxqlnIjg0CDX60V71GUVQLWAvKTlNh0QUg0TMc5SxTvGbrvpeg
  template:
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: ingress
    type: kubernetes.io/dockerconfigjson
