apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeflix-radarr
  namespace: argocd
spec:
  project: homeflix
  source:
    path: helm/homelab-application
    repoURL: ssh://git@git-ssh.aleix.cloud:2222/alemuro/argocd-homelab.git
    targetRevision: HEAD
    helm:
      releaseName: radarr
      values: |
        name: radarr
        image: lscr.io/linuxserver/radarr
        tag: latest
        port: 7878
        domains:
          - radarr.immaleix.casa
        mount:
          /mnt/local/configs/radarr: /config
          /mnt/nfs/homeflix-v2: /media
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        allow_from:
          - prowlarr
          - overseerr
          - bazarr
          - maintainerr
          - radarr-exporter
          - sizeondisk-exporter
          - discovarr
  destination:
    name: homelab
    namespace: homeflix
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
