apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homeflix-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: ssh://git@git-ssh.aleix.cloud:2222/alemuro/argocd-homelab.git
        revision: HEAD
        files:
          - path: "applications/homeflix/apps/*.yaml"
  template:
    metadata:
      name: 'homeflix-{{.name}}'
      {{- if .image_updater }}
      {{- if .image_updater.enabled }}
      annotations:
        argocd-image-updater.argoproj.io/image-list: "app-image={{ .image }}"
        argocd-image-updater.argoproj.io/app-image.update-strategy: "{{ .image_updater.strategy | default "semver" }}"
        {{- if .image_updater.allow_tags }}
        argocd-image-updater.argoproj.io/app-image.allow-tags: "{{ .image_updater.allow_tags }}"
        {{- end }}
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/write-back-repository: "ssh://git@git-ssh.aleix.cloud:2222/alemuro/argocd-homelab.git"
      {{- end }}
      {{- end }}
    spec:
      project: homeflix
      source:
        path: helm/homelab-application
        repoURL: ssh://git@git-ssh.aleix.cloud:2222/alemuro/argocd-homelab.git
        targetRevision: HEAD
        helm:
          values: |
            {{- toYaml . | nindent 12 }}
      destination:
        name: homelab
        namespace: homeflix
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
