name: "backups-monitors"
title: "Backups Monitors"
folderUid: "bds4wss5qivwgc"
intervalSeconds: 60

rules:
  - name: "Backup failed (worker-0)"
    condition: "A"
    for: "5m"
    from: 300
    to: 0
    datasourceUid: "grafanacloud-logs"
    summary: "worker-0 Backup failed"
    description: "Backup for worker-0 failed"
    expr: '(sum(count_over_time({service_name="restic-worker-0"} |~ "snapshot .+ saved"[1d])) or vector(0)) < 1'

  - name: "Backup failed (worker-1)"
    condition: "A"
    for: "5m"
    from: 300
    to: 0
    datasourceUid: "grafanacloud-logs"
    summary: "worker-1 Backup failed"
    description: "Backup for worker-1 failed"
    expr: '(sum(count_over_time({service_name="restic-worker-1"} |~ "snapshot .+ saved"[1d])) or vector(0)) < 1'

  - name: "Backup failed (summer)"
    condition: "A"
    for: "5m"
    from: 300
    to: 0
    datasourceUid: "grafanacloud-logs"
    summary: "summer Backup failed"
    description: "Backup for summer failed"
    expr: '(sum(count_over_time({service_name="restic-summer"} |~ "snapshot .+ saved"[1d])) or vector(0)) < 1'
