name: "pods-monitors"
title: "Pods Monitors"
folderUid: "bds4wss5qivwgc"
intervalSeconds: 60

rules:
  - name: "Pod CPU above request"
    condition: "A"
    for: "10m"
    from: 600
    to: 0
    datasourceUid: "grafanacloud-prom"
    operator: "above"
    threshold: 1
    summary: "Pod {{$labels.namespace}}/{{$labels.pod}} CPU above request"
    description: "Pod {{$labels.pod}} in {{$labels.namespace}} has been using more CPU than its request for 10+ minutes"
    expr: 'sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{container!="",namespace=~"homeflix|homelab"}[5m])) / sum by (pod, namespace) (kube_pod_container_resource_requests{resource="cpu",namespace=~"homeflix|homelab"})'

  - name: "Pod Memory above request"
    condition: "A"
    for: "10m"
    from: 600
    to: 0
    datasourceUid: "grafanacloud-prom"
    operator: "above"
    threshold: 1
    summary: "Pod {{$labels.namespace}}/{{$labels.pod}} Memory above request"
    description: "Pod {{$labels.pod}} in {{$labels.namespace}} has been using more memory than its request for 10+ minutes"
    expr: 'sum by (pod, namespace) (container_memory_working_set_bytes{container!="",namespace=~"homeflix|homelab"}) / sum by (pod, namespace) (kube_pod_container_resource_requests{resource="memory",namespace=~"homeflix|homelab"})'
