name: "services-monitors"
title: "Services Monitors"
folderUid: "bds4wss5qivwgc"
intervalSeconds: 60

rules:
  - name: "Service not reachable"
    condition: "A"
    for: "5m"
    from: 300
    to: 0
    datasourceUid: "grafanacloud-prom"
    summary: "Service {{$labels.cluster}}/{{$labels.kubernetes_namespace}}/{{$labels.k8s_app}} not reachable"
    description: "Service {{$labels.service}} is not reachable"
    expr: 'min(probe_success{job="prometheus.scrape.healthchecks",service=~"radarr|sonarr|plex|qbittorrent|bazarr|overseerr|prowlarr|tautulli|dns1|dns2|consul|openbao|uptime|vaultwarden|cloudweatherproxy|gloriarelats|jocdelsmunicipis-api"}) by(service, kubernetes_namespace, k8s_app, cluster) < 1'
